"""initial schema

All tables from the approved Phase 1 design, plus:
- mediverse_tags_text(): IMMUTABLE wrapper so tags can feed the generated search_vector column
  (array_to_string is only STABLE, which generated columns reject)
- speed_feed_items AFTER INSERT trigger -> pg_notify('speed_feed', id): lets every API worker
  push new items to its own WebSocket clients without Redis
- the 7 topic categories (reference data the site nav needs in every environment)

Revision ID: 0f371ba34bfc
Revises:
Create Date: 2026-09-29 11:13:02.059747
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0f371ba34bfc"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


CATEGORIES = [
    # slug, name, sort_order, is_primary (a dossier's main category is one of the primary three)
    ("pharma", "Pharma & Biologics", 1, True),
    ("regulatory", "Regulatory & CDSCO", 2, False),
    ("medtech", "MedTech & Robotics", 3, True),
    ("ai-health", "AI & Digital Health", 4, True),
    ("clinical", "Clinical Operations", 5, False),
    ("supply-chain", "Supply Chain & Logistics", 6, False),
    ("market-access", "Market Access & HEOR", 7, False),
]


def upgrade() -> None:
    op.execute(
        """
        CREATE FUNCTION mediverse_tags_text(tags text[]) RETURNS text
        LANGUAGE sql IMMUTABLE PARALLEL SAFE
        AS $$ SELECT coalesce(array_to_string(tags, ' '), '') $$
        """
    )
    # ### commands auto generated by Alembic (reviewed) ###
    op.create_table(
        "authors",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("role", sa.String(length=160), nullable=True),
        sa.Column("company", sa.String(length=160), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("photo_url", sa.Text(), nullable=True),
        sa.Column("linkedin_url", sa.Text(), nullable=True),
        sa.Column("expertise", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("credentials", sa.String(length=200), nullable=True),
        sa.Column("location", sa.String(length=120), nullable=True),
        sa.Column("is_contributor", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_authors")),
        sa.UniqueConstraint("slug", name=op.f("uq_authors_slug")),
    )
    op.create_table(
        "categories",
        sa.Column("id", sa.SmallInteger(), autoincrement=True, nullable=False),
        sa.Column("slug", sa.String(length=48), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("sort_order", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("is_primary", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("name", name=op.f("uq_categories_name")),
        sa.UniqueConstraint("slug", name=op.f("uq_categories_slug")),
    )
    op.create_table(
        "issues",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("slug", sa.String(length=48), nullable=False),
        sa.Column("issue_number", sa.Integer(), nullable=False),
        sa.Column("volume", sa.String(length=32), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("month_year", sa.Date(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("cover_image_url", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="draft", nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("editorial_column", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("macro_signals", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("readers_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('draft', 'published', 'archived')", name=op.f("ck_issues_status_valid")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_issues")),
        sa.UniqueConstraint("issue_number", name=op.f("uq_issues_issue_number")),
        sa.UniqueConstraint("month_year", name=op.f("uq_issues_month_year")),
        sa.UniqueConstraint("slug", name=op.f("uq_issues_slug")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.Text(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("role", sa.String(length=16), server_default="reader", nullable=False),
        sa.Column("tier", sa.String(length=16), server_default="free", nullable=False),
        sa.Column("email_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("role IN ('reader', 'editor', 'admin')", name=op.f("ck_users_role_valid")),
        sa.CheckConstraint(
            "tier IN ('free', 'professional', 'enterprise')", name=op.f("ck_users_tier_valid")
        ),
        sa.CheckConstraint("email = lower(email)", name=op.f("ck_users_email_lowercase")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "dossiers",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("deck", sa.Text(), nullable=False),
        sa.Column(
            "body",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("sections", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("references", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("cover_image_url", sa.Text(), nullable=True),
        sa.Column("format", sa.String(length=16), server_default="feature", nullable=False),
        sa.Column("primary_category_id", sa.SmallInteger(), nullable=False),
        sa.Column("issue_id", sa.BigInteger(), nullable=True),
        sa.Column("author_id", sa.BigInteger(), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("read_time_minutes", sa.SmallInteger(), nullable=False),
        sa.Column("is_featured", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_locked", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="draft", nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "setweight(to_tsvector('english', coalesce(title, '')), 'A') || setweight(to_tsvector('english', coalesce(deck, '')), 'B') || setweight(to_tsvector('english', mediverse_tags_text(tags)), 'C') || setweight(jsonb_to_tsvector('english', body, '[\"string\"]'), 'D')",
                persisted=True,
            ),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "format IN ('feature', 'analysis', 'interview', 'digest')", name=op.f("ck_dossiers_format_valid")
        ),
        sa.CheckConstraint("jsonb_typeof(body) = 'array'", name=op.f("ck_dossiers_body_is_array")),
        sa.CheckConstraint("slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'", name=op.f("ck_dossiers_slug_format")),
        sa.CheckConstraint(
            "status = 'draft' OR published_at IS NOT NULL", name=op.f("ck_dossiers_published_has_date")
        ),
        sa.CheckConstraint("status IN ('draft', 'published')", name=op.f("ck_dossiers_status_valid")),
        sa.CheckConstraint("read_time_minutes > 0", name=op.f("ck_dossiers_read_time_positive")),
        sa.ForeignKeyConstraint(
            ["author_id"], ["authors.id"], name=op.f("fk_dossiers_author_id_authors"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["issue_id"], ["issues.id"], name=op.f("fk_dossiers_issue_id_issues"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["primary_category_id"],
            ["categories.id"],
            name=op.f("fk_dossiers_primary_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dossiers")),
        sa.UniqueConstraint("slug", name=op.f("uq_dossiers_slug")),
    )
    op.create_index(op.f("ix_dossiers_author_id"), "dossiers", ["author_id"], unique=False)
    op.create_index(op.f("ix_dossiers_issue_id"), "dossiers", ["issue_id"], unique=False)
    op.create_index(
        op.f("ix_dossiers_primary_category_id"), "dossiers", ["primary_category_id"], unique=False
    )
    op.create_index(
        "ix_dossiers_search_vector", "dossiers", ["search_vector"], unique=False, postgresql_using="gin"
    )
    op.create_index(
        "ix_dossiers_status_published_at",
        "dossiers",
        ["status", sa.literal_column("published_at DESC")],
        unique=False,
    )
    op.create_index("ix_dossiers_tags", "dossiers", ["tags"], unique=False, postgresql_using="gin")
    op.create_table(
        "newsletter_subscribers",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column("confirm_token_hash", sa.String(length=64), nullable=True),
        sa.Column("confirm_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("unsubscribe_token_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "subscribed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("unsubscribed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'confirmed', 'unsubscribed')",
            name=op.f("ck_newsletter_subscribers_status_valid"),
        ),
        sa.CheckConstraint("email = lower(email)", name=op.f("ck_newsletter_subscribers_email_lowercase")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_newsletter_subscribers_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_newsletter_subscribers")),
        sa.UniqueConstraint("confirm_token_hash", name=op.f("uq_newsletter_subscribers_confirm_token_hash")),
        sa.UniqueConstraint("email", name=op.f("uq_newsletter_subscribers_email")),
        sa.UniqueConstraint(
            "unsubscribe_token_hash", name=op.f("uq_newsletter_subscribers_unsubscribe_token_hash")
        ),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by", sa.UUID(), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["replaced_by"],
            ["refresh_tokens.id"],
            name=op.f("fk_refresh_tokens_replaced_by_refresh_tokens"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_refresh_tokens_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_tokens_token_hash")),
    )
    op.create_index(op.f("ix_refresh_tokens_family_id"), "refresh_tokens", ["family_id"], unique=False)
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "speed_feed_items",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("headline", sa.String(length=300), nullable=False),
        sa.Column("detail", sa.Text(), server_default="", nullable=False),
        sa.Column("source", sa.String(length=120), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("is_breaking", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("read_time_minutes", sa.SmallInteger(), nullable=True),
        sa.Column(
            "published_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "category IN ('Drug Approvals', 'CDSCO & Policy', 'Cold Chain', 'Biotech', 'Commercial BD', 'AI-Health')",
            name=op.f("ck_speed_feed_items_category_valid"),
        ),
        sa.CheckConstraint(
            "read_time_minutes IS NULL OR read_time_minutes > 0",
            name=op.f("ck_speed_feed_items_read_time_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_speed_feed_items_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_speed_feed_items")),
    )
    op.create_index(
        "ix_speed_feed_published",
        "speed_feed_items",
        [sa.literal_column("published_at DESC"), sa.literal_column("id DESC")],
        unique=False,
    )
    op.create_table(
        "user_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "purpose IN ('verify_email', 'reset_password')", name=op.f("ck_user_tokens_purpose_valid")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_tokens_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_user_tokens_token_hash")),
    )
    op.create_index(op.f("ix_user_tokens_user_id"), "user_tokens", ["user_id"], unique=False)
    op.create_table(
        "dossier_categories",
        sa.Column("dossier_id", sa.BigInteger(), nullable=False),
        sa.Column("category_id", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_dossier_categories_category_id_categories"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["dossier_id"],
            ["dossiers.id"],
            name=op.f("fk_dossier_categories_dossier_id_dossiers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("dossier_id", "category_id", name=op.f("pk_dossier_categories")),
    )
    op.create_index(
        op.f("ix_dossier_categories_category_id"), "dossier_categories", ["category_id"], unique=False
    )
    op.create_table(
        "saved_items",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("dossier_id", sa.BigInteger(), nullable=False),
        sa.Column("saved_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["dossier_id"],
            ["dossiers.id"],
            name=op.f("fk_saved_items_dossier_id_dossiers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_saved_items_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "dossier_id", name=op.f("pk_saved_items")),
    )
    op.create_index(
        "ix_saved_items_user_saved_at",
        "saved_items",
        ["user_id", sa.literal_column("saved_at DESC")],
        unique=False,
    )
    # ### end Alembic commands ###

    op.execute(
        """
        CREATE FUNCTION speed_feed_notify() RETURNS trigger
        LANGUAGE plpgsql
        AS $$ BEGIN PERFORM pg_notify('speed_feed', NEW.id::text); RETURN NEW; END $$
        """
    )
    op.execute(
        "CREATE TRIGGER speed_feed_items_notify AFTER INSERT ON speed_feed_items "
        "FOR EACH ROW EXECUTE FUNCTION speed_feed_notify()"
    )

    categories = sa.table(
        "categories",
        sa.column("slug", sa.String),
        sa.column("name", sa.String),
        sa.column("sort_order", sa.SmallInteger),
        sa.column("is_primary", sa.Boolean),
    )
    op.bulk_insert(
        categories,
        [{"slug": s, "name": n, "sort_order": o, "is_primary": p} for s, n, o, p in CATEGORIES],
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS speed_feed_items_notify ON speed_feed_items")
    op.execute("DROP FUNCTION IF EXISTS speed_feed_notify()")
    # ### commands auto generated by Alembic (reviewed) ###
    op.drop_index("ix_saved_items_user_saved_at", table_name="saved_items")
    op.drop_table("saved_items")
    op.drop_index(op.f("ix_dossier_categories_category_id"), table_name="dossier_categories")
    op.drop_table("dossier_categories")
    op.drop_index(op.f("ix_user_tokens_user_id"), table_name="user_tokens")
    op.drop_table("user_tokens")
    op.drop_index("ix_speed_feed_published", table_name="speed_feed_items")
    op.drop_table("speed_feed_items")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_family_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_table("newsletter_subscribers")
    op.drop_index("ix_dossiers_tags", table_name="dossiers", postgresql_using="gin")
    op.drop_index("ix_dossiers_status_published_at", table_name="dossiers")
    op.drop_index("ix_dossiers_search_vector", table_name="dossiers", postgresql_using="gin")
    op.drop_index(op.f("ix_dossiers_primary_category_id"), table_name="dossiers")
    op.drop_index(op.f("ix_dossiers_issue_id"), table_name="dossiers")
    op.drop_index(op.f("ix_dossiers_author_id"), table_name="dossiers")
    op.drop_table("dossiers")
    op.drop_table("users")
    op.drop_table("issues")
    op.drop_table("categories")
    op.drop_table("authors")
    # ### end Alembic commands ###
    op.execute("DROP FUNCTION IF EXISTS mediverse_tags_text(text[])")
